using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

public class AutoTerrainGeneratorTool : EditorWindow
{
    private int objectCount = 10; // 생성할 오브젝트 수
    private GameObject parent; // 생성할 프리팹의 부모
    private GameObject prefab; // 생성할 프리팹
    private Vector3 startPosition = Vector3.zero; // 시작 위치
    
    private Vector2Int minRange = new Vector2Int(-20,-20);
    private Vector2Int maxRange = new Vector2Int(20,20);
    
    private Texture2D heightMap;
    
    [MenuItem("Tools/Auto Terrain Generate Tool")]
    public static void ShowWindow()
    {
        GetWindow<AutoTerrainGeneratorTool>("Auto Terrain Generate Tool");
    }

    private void OnGUI()
    {
        GUILayout.Label("게임 오브젝트 자동 배치", EditorStyles.boldLabel);
        
        objectCount = EditorGUILayout.IntField("오브젝트 수:", objectCount);
        parent = (GameObject)EditorGUILayout.ObjectField("부모 오브젝트", parent, typeof(GameObject), true);
        prefab = (GameObject)EditorGUILayout.ObjectField("프리팹:", prefab, typeof(GameObject), false);
        startPosition = EditorGUILayout.Vector3Field("시작 위치:", startPosition);
        minRange = EditorGUILayout.Vector2IntField("최소 범위", minRange);
        maxRange = EditorGUILayout.Vector2IntField("최대 범위", maxRange);
        
        heightMap = EditorGUILayout.ObjectField("높이 텍스처", heightMap, typeof(Texture2D), false) as Texture2D;

        if (GUILayout.Button("생성 및 배치"))
        {
            CreateAndPlaceObjects();
        }
    }

    private void ClearTerrain()
    {
        List<GameObject> childrensToDestroy = new List<GameObject>();
        for (int i = 0; i < parent.transform.childCount; i++)
        {
            childrensToDestroy.Add(parent.transform.GetChild(i).gameObject);
        }
        foreach (var children in childrensToDestroy)
        {
            DestroyImmediate(children);
        }
        childrensToDestroy.Clear();

    }

    void CreateTerrainMesh()
    {
        var meshFilter = prefab.GetComponent<MeshFilter>();
        var mesh = meshFilter.sharedMesh;

        Color[] pixels = heightMap.GetPixels();

        // get vertices
        // 1. Get the vertices of the mesh
        List<Vector3> vertices = new List<Vector3>();
        mesh.GetVertices(vertices);
        
        // 2. Get the UVs of the mesh
        List<Vector2> uvs = new List<Vector2>();
        mesh.GetUVs(0, uvs);
    }
    
    private void CreateAndPlaceObjects()
    {
        if (parent == null)
        {
            Debug.LogError("부모를 설정해주세요!");
            return;
        }
        
        if (prefab == null)
        {
            Debug.LogError("프리팹을 설정해주세요!");
            return;
        }

        ClearTerrain();

        var meshFilter = prefab.GetComponent<MeshFilter>();
        var mesh = meshFilter.sharedMesh;
        
        var bounds = mesh.bounds;
        var offset = bounds.extents * 2.0f;
        
        for (int x = minRange.x; x < maxRange.x; x++)
        {
            for (int y = minRange.y; y < maxRange.y; y++)
            {
                Vector3 position = startPosition + new Vector3(x * offset.x, 0,  y * offset.z); // 간격을 두고 생성
                GameObject obj = Instantiate(prefab, position, Quaternion.identity);
                obj.transform.SetParent(parent.transform);
                obj.name = $"AutoGenerated_{x}_{y}"; // 이름 설정
                
                //CreateTerrainMesh(obj);
            }
        }
        
    }
    
    void CreateTerrainMesh(GameObject terrain)
    {
        var meshFilter = terrain.GetComponent<MeshFilter>();
        var originalMesh = meshFilter.sharedMesh;

        // 새로운 Mesh 생성
        Mesh newMesh = new Mesh();

        // 기존 Mesh의 데이터 복사
        newMesh.vertices = originalMesh.vertices;
        newMesh.triangles = originalMesh.triangles;
        newMesh.uv = originalMesh.uv;
        newMesh.normals = originalMesh.normals;
        newMesh.tangents = originalMesh.tangents;
        newMesh.colors = originalMesh.colors;

        // SubMesh 데이터 복사
        newMesh.subMeshCount = originalMesh.subMeshCount;
        for (int i = 0; i < originalMesh.subMeshCount; i++)
        {
            newMesh.SetIndices(originalMesh.GetIndices(i), originalMesh.GetTopology(i), i);
        }
        
        List<Vector3> vertices = new List<Vector3>();
        originalMesh.GetVertices(vertices);

        var pixels = heightMap.GetPixels();

        for (int i = 0; i < vertices.Count; i++)
        {
            var wp = terrain.transform.TransformPoint(vertices[i]);
            Vector2 uv = new Vector2(wp.x / heightMap.width, wp.z / heightMap.height);
            uv *= 2f;
            
            Color pixel = heightMap.GetPixelBilinear(uv.x , uv.y);

            var vector3 = vertices[i];
            vector3.y += pixel.a * 60f; // 높이 조정
            vertices[i] = vector3;
        }
        
        newMesh.SetVertices(vertices);
        
        // Bounds 및 기타 데이터 갱신
        newMesh.RecalculateBounds();
        newMesh.RecalculateNormals();
        newMesh.RecalculateTangents();

        // 새로운 Mesh를 MeshFilter에 설정
        meshFilter.mesh = newMesh;
        
        var assetName = terrain.name + "_Mesh";
        SaveMeshAsset(newMesh, assetName);
    }
    
    public void SaveMeshAsset(Mesh mesh, string assetName)
    {
        if (mesh == null)
        {
            Debug.LogError("저장할 Mesh가 없습니다.");
            return;
        }

        // 저장 경로 설정
        string path = $"Assets/01.InGame/Terrain/Level/{assetName}.asset";

        // 에셋 생성
        AssetDatabase.CreateAsset(mesh, path);
        AssetDatabase.SaveAssets();

        Debug.Log($"Mesh가 {path} 경로에 저장되었습니다.");
    }
}

